sudo: required
services:
  - docker

before_install:
  - docker build -t srihachi/docker-react -f Dockerfile-dev .

script:
  - docker run srihachi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-365157644567"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEYS
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

